name: 'Chromatic'

on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'
      - uses: ./.github/actions/setup_takumi_guard_npm
        with:
          bot-id: ${{ vars.TAKUMI_GUARD_BOT_ID }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test Takumi Guard
        run: pnpm install @panda-guard/test-malicious

      - name: Publish to Chromatic
        uses: chromaui/action@v13
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true # 👈 Required option to enable TurboSnap
