name: CI Release
on:
  release:
    types: [created]
jobs: 
  test_release: 
    name: Check release
    runs-on: ubuntu-18.04
    steps: 
      - uses: actions/checkout@master
      - name: Remove package-lock
        run: rm -rf package-lock.json
      - name: docker name
        id: docker
        uses: actions/test_docker
        with:
          who-to-greet: Mona the Octocat
      - name: Get the output time
        run: echo "The time was ${{ steps.docker.outputs.time }}"
      
      
      
      
  
      


