name: CI Release
on:
  release:
    types: [created]
jobs: 
  test_release: 
    name: Check release
    runs-on: ubuntu-18.04 
    steps:
      - name: checkout 
        uses: actions/checkout@master
      - name: Get version
        run: echo "::set-output name=version::$(npm run package-version)"
        id: get_version
      - name: Show version
        run: echo "${{steps.get_version.version}}"
