name: CI Release
on: 
  repository_dispatch:
    types: test_dispatch
jobs: 
  test_release: 
    name: Check release
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.head_ref }}
      - name: test repo dispatch
        uses: ./actions/test_repo_dispatch
      
          
      
      
  
      


