name: CI Release
on: 
  repository_dispatch:
    types: test_dispatch
  release:
    types: [published]
jobs: 
  test_release: 
    name: Check release
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.head_ref }}
      - name: get4
        run: |
          curl -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization:token ${{secrets.github_action}}"  --request POST https://api.github.com/repos/SDQA-VN/ui-component-auto/dispatches --data '{"event_type": "kuc-trigger-auto-test"}'
      - name: get5
        if: contains(github.event.client_payload.unit,true)
        run: "echo fail"
      - name: get 7
        if: contains(github.event.client_payload.unit,true)
        run: "echo next step"
      - name: get 6
        if: contains(github.event.client_payload.unit,true)
        run: "echo next step"
  
      


