name: CI Release
on:
  release:
    types: [created]
jobs: 
  test_release: 
    name: Check release
    runs-on: ubuntu-18.04
    steps: 
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get integrity
        uses: ./actions/get_integrity
      - name: access permission
        run: chmod +x ./actions/test_docker/entrypoint.sh
      - name: docker name
        id: docker
        uses: ./actions/test_docker
        with:
          who-to-greet: Mona the Octocat
      - name: Get the output time
        run: echo "The time was ${{ steps.docker.outputs.time }}"
      
      
      
      
  
      


