name: CI Release
on:
  release:
    types: [created]
jobs: 
  test_release: 
    name: Check release
    runs-on: ubuntu-18.04
    steps: 
      - uses: actions/checkout@master
      - name: Remove package-lock
        run: rm -rf package-lock.json
      - name: Install dependencies
        run: npm install
      - name: build 
        if: success()
        run: npm run build
      - name: Check version
        if: success()
        run: npm run check:release 
      - name: Prepare package
        if: success()
        run: npm pack
      - name: context
        env: 
          myString: ${{ '../../package.json' }} 
        run: echo "$myString"
      - name: Upload package to release[binaries]
        uses: svenstaro/upload-release-action@v1-release
        with: 
          repo_token: ${{ secrets.ACCESS_TOKEN }}
          file: kintone-kintone-ui-component-${{ github.ref }}
          asset_name: kintone-kintone-ui-component-0.0.34.tgz
          tag: ${{ github.ref }}
          overwrite: true
  
      


