name: CI Release
on:
  release:
    types: [created]
jobs: 
  test_release: 
    name: Check release
    runs-on: ubuntu-18.04 
    steps:
      - name: checkout 
        uses: actions/checkout@master
      - name: get version
        id: get_version
        uses: actions/github-script@0.2.0
        with:
         github-token: ${{ secrets.ACCESS_TOKEN }}
         script: return "0.3.4";
      - name: Get version
        run: echo "${{steps.get_version.result}}"
