name: CI Release
on:
  release:
    types: [created]
jobs: 
  test_release: 
    name: Check release
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Remove package-lock
        if: success()      
        run: rm -rf package-lock.json
      - name: Install dependencies
        run: npm install
      - name: deploy master
        if: success()
        run: |
          ls -l
          git config --global user.email "phamgiahuong2012@gmail.com"
          git config --global user.name "huong"
          git remote set-url origin https://Pham-Gia-Huong:${{secrets.ACCESS_TOKEN}}@github.com/Pham-Gia-Huong/kintone-ui-component.git
          git add dist
          git commit -m "merge release"
          git push origin HEAD:master --force
      - name: Upload package to release[binaries]
        uses: svenstaro/upload-release-action@v1-release
        with: 
          repo_token: ${{ secrets.ACCESS_TOKEN }}
          file: kintone-kintone-ui-component-${{ steps.check_version.outputs.version }}.tgz
          asset_name: kintone-kintone-ui-component-${{ steps.check_version.outputs.version }}.tgz
          tag: ${{ github.ref }}
          overwrite: true
      
          
      
      
  
      


