name: CI Release
on: 
  repository_dispatch:
    types: test_dispatch
jobs: 
  test_release: 
    name: Check release
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.head_ref }}
      - name: get4
        if: contains(github.event.client_payload.unit,false)
        run: "echo pass"
      - name: get5
        if: contains(github.event.client_payload.unit,true)
        run: "echo fail"
      - name: get 7
        if: cancelled()
        run: "echo next step"
      - name: get 6
        run: "echo next step"
  
      


