name: CI Release
on:
  release:
    types: [created]
jobs: 
  test_release: 
    name: Check release
    runs-on: ubuntu-18.04 
    steps:
      - name: checkout 
        uses: actions/checkout@master
      - name: Get version
        run: echo "${{ format('kintone-kintone-ui-component-{0}.tgz', $(npm run package-version)) }}"
        id: get_version
