name: CI Release
on:
  release:
    types: [created]
jobs: 
  test_release: 
    name: Check release
    runs-on: ubuntu-18.04
    steps: 
      - name: Checkout
        uses: actions/checkout@v1
      - name: install dependence
        run: npm install
      - name: Get integrity
        id: get_integrity
        uses: ./actions/get_integrity
      - name: show integrity output
        run: eco  "This is my integrity:${{steps.get_integrity.outputs.integrity}}"
      - name: upload integrity
        if: success()
        uses: actions/upload-artifact@master
        with:
          name: my-integrity
          path: ./integrity.txt        
      - name: access permission
        run: chmod +x ./actions/test_docker/entrypoint.sh
      - name: docker name
        id: docker
        uses: ./actions/test_docker
        with:
          who-to-greet: Mona the Octocat
      - name: Get the output time
        run: echo "The time was ${{ steps.docker.outputs.time }}"
      
      
      
      
  
      


