name: CI Release
on:
  release:
    types: [created]
jobs: 
  test_release: 
    name: Check release
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Remove package-lock
        if: success()      
        run: rm -rf package-lock.json
      - name: Install dependencies
        run: npm install
      - name: deploy master
        if: success()
        run: |
          ls -l
          git status
          git commit package.json -m "test" 
      - name: Upload package to release[binaries]
        uses: svenstaro/upload-release-action@v1-release
        with: 
          repo_token: ${{ secrets.ACCESS_TOKEN }}
          file: kintone-kintone-ui-component-${{ steps.check_version.outputs.version }}.tgz
          asset_name: kintone-kintone-ui-component-${{ steps.check_version.outputs.version }}.tgz
          tag: ${{ github.ref }}
          overwrite: true
      
          
      
      
  
      


