name: CI Release
on:
  release:
    types: [created]
jobs: 
  test_release: 
    name: Check release
    runs-on: ubuntu-18.04
    steps: 
      - uses: actions/checkout@master
      - name: Remove package-lock
        run: rm -rf package-lock.json
      - name: Install dependencies
        run: npm install
      - name: build 
        if: success()
        run: npm run build
      - name: Check version
        if: success()
        id: check_version
        uses: ./actions/action.yml
      - name: get version
        run: echo "${{ steps.check_version.outputs.version }}"
  
      


