name: CI Release
on:
  release:
    types: [created]
jobs: 
  test_release: 
    name: Check release
    runs-on: ubuntu-18.04 
    steps: 
      - uses: actions/checkout@master
      - name: Get version
        run: echo "test"
        id: build_package
        outputs:
          version: "$(npm run package-version)"
      - name: print
        run: echo "steps.build_package.outputs.version"
  
      


