name: CI Release
on:
  release:
    types: [created]
jobs: 
  test_release: 
    name: Check release
    runs-on: ubuntu-18.04
    steps: 
      - name: Checkout
        uses: actions/checkout@v1
      - name: install dependence
        run: npm install
      - name: Get integrity
        id: get_integrity
        uses: ./actions/get_integrity
      - name: show integrity output
        run: echo  "This is my integrity:${{steps.get_integrity.outputs.integrity}}"
      - name: upload integrity
        if: success()
        uses: actions/upload-artifact@master
        with:
          name: my-integrity
          path: ./integrity.txt        
      - name: create input using docker
        id: docker
        uses: ./actions/test_docker
        with:
          docker-input: "test input docker" 
      - name: Get the output time
        run: echo "The time was ${{ steps.docker.outputs.time }}"
      
      
      
      
  
      


