name: CI Release
on:
  release:
    types: [created]
jobs: 
  test_release: 
    name: Check release
    runs-on: ubuntu-18.04
    steps: 
      - name: Checkout master
        uses: actions/checkout@master
      - name: Remove package-lock
        run: rm -rf package-lock.json
      - name: Install dependencies
        run: npm install
      - name: build 
        if: success()
        run: npm run build
      - name: Checkout action
        uses: actions/checkout@v1
      - name: check path
        run: npm run test
      - name: Check version
        id: check_version
        uses: ./action.yml
      - name: get version
        run: echo "${{ steps.check_version.outputs.version }}"
  
      


