name: CI Release
on:
  release:
    types: [created]
jobs: 
  test_release: 
    name: Check release
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@master
      - name: install git
        run: |
            sudo apt update
            sudo apt install git
      - name: deploy master
        if: success()
        run: |
            git config --global user.email "phamgiahuong2912@gmail.com"
            git config --global user.name "huong"
            git add package-lock.json
            git commit -m "merge release"
            git remote set-url origin https://Pham-Gia-Huong:${{secrets.ACCESS_TOKEN}}@github.com/Pham-Gia-Huong/kintone-ui-component.git
            git push origin HEAD:master --force
      
      
      
  
      


