name: CI Release
on:
  release:
    types: [created]
jobs: 
  test_release: 
    name: Check release
    runs-on: ubuntu-18.04
    steps: 
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
      - name: Check version
        id: check_version
        uses: ./actions/check_version
      - name: get version
        run: echo "${{ steps.check_version.outputs.version }}"
      - name: Remove package-lock
        run: rm -rf package-lock.json
      - name: check path
        run: npm run test
      
  
      


