name: CI Release
on: 
  repository_dispatch:
    types: test_dispatch
  release:
    types: [published]
jobs: 
  test_release: 
    name: Check release
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.head_ref }}
      - name: Repository Dispatch
        if: contains(github.event.client_payload.status,fail)
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{secrets.ACCESS_TOKEN}}
          repository: SDQA-VN/ui-component-auto
          event-type: kuc-trigger-auto-test
      - name: echo
          run: echo ${{ github.event.client_payload.status }}
  
      


