name: CI Release
on:
  release:
    types: [created]
jobs: 
  test_release: 
    name: Check release
    runs-on: ubuntu-18.04 
    steps: 
      - uses: actions/checkout@master
      - name: Get version
        run: echo "##[set-output name=version;]$(echo 0.1.2)"
        id: get_version
      - name: print
        run: echo "steps.get_version.outputs.version"
