name: CI Release
on: 
  repository_dispatch:
    types: test_dispatch
  release:
    types: [published]
jobs: 
  test_release: 
    name: Check release
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.head_ref }}
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: 8a70d998c074b5da50ac9d7ea9c22c4842682cb4
          repository: SDQA-VN/ui-component-auto
          event-type: kuc-trigger-auto-test
      - name: get5
        if: contains(github.event.client_payload.unit,true)
        run: "echo fail"
      - name: get 7
        if: contains(github.event.client_payload.unit,true)
        run: "echo next step"
      - name: get 6
        if: contains(github.event.client_payload.unit,true)
        run: "echo next step"
  
      


