name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: hecrj/setup-rust-action@v1-release
      with:
        rust-version: stable
    - uses: actions/checkout@v1
    - name: Build
      run: npm run build
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with: 
        repo_token: ${{ secrets.ACCESS_TOKEN }}
        file: kintone-kintone-ui-component-0.0.11.tgz
        asset_name: kintone-kintone-ui-component-0.0.11.tgz
        tag: ${{ github.ref }}
        overwrite: true