name: CI Release
on:
  release:
    types: [created]
jobs: 
  test_release: 
    name: Check release
    runs-on: ubuntu-18.04
    steps: 
      - uses: actions/checkout@master
      - name: Install dependence
        run: npm install
      - name: Check version
        if: success()
        run: npm run check-release
      - name: Process package
        if: success()
        run: npm pack
     
  
      


