name: CI Release
on:
  release:
    types: [created]
jobs: 
  test_release: 
    name: Check release
    runs-on: ubuntu-18.04
    steps: 
      - uses: actions/checkout@master
      - name: Remove package-lock
        run: rm -rf package-lock.json
      - name: Install dependence
        run: npm install
      - name: build 
        if: success()
        run: npm run build
      - name: Check version
        if: success()
        run: npm run check:release
      - name: Process package
        if: success()
        run: npm pack 
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with: 
          repo_token: ${{ secrets.ACCESS_TOKEN }}
          file: kintone-kintone-ui-component-0.0.33.tgz
          asset_name: kintone-kintone-ui-component-0.0.33.tgz
          tag: ${{ github.ref }}
          overwrite: true
      - name: deploy master
        if: success()
        run: |
          git config --global user.email "phamgiahuong2912@gmail.com"
          git config --global user.name "huong"
          git add esm dist
          git commit -m "merge release"
          git remote set-url origin https://Pham-Gia-Huong:${{secrets.ACCESS_TOKEN}}@github.com/Pham-Gia-Huong/kintone-ui-component.git
          git push origin HEAD:master --force
  
      


